2017-08-14 09:58:00,170 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,172 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 2.14ms
2017-08-14 09:58:00,177 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,178 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.39ms
2017-08-14 09:58:00,183 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,184 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.22ms
2017-08-14 09:58:00,189 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,190 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.34ms
2017-08-14 09:58:00,195 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,196 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.29ms
2017-08-14 09:58:00,202 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,202 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.94ms
2017-08-14 09:58:00,208 - tornado.general - web.py[line:1545] - WARNING - 403 POST /login.action (47.52.17.164): '_xsrf' argument missing from POST
2017-08-14 09:58:00,209 - tornado.access - web.py[line:1971] - WARNING - 403 POST /login.action (47.52.17.164) 1.29ms
2017-08-14 12:25:36,599 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://clientapi.ipip.net/echo.php?info=1234567890 (139.162.81.62) 2.05ms
2017-08-14 12:25:36,605 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-14 17:10:20,265 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.225.205) 2.31ms
2017-08-14 17:33:00,844 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.225.205) 1.97ms
2017-08-14 19:06:49,162 - tornado.access - web.py[line:1971] - WARNING - 405 GET /phpmyadmin/index.php (47.52.17.164) 2.84ms
2017-08-14 19:06:49,165 - tornado.access - web.py[line:1971] - WARNING - 405 GET /phpmyadmin/index.php (47.52.17.164) 1.34ms
2017-08-15 07:07:25,148 - tornado.access - web.py[line:1971] - WARNING - 405 GET /tree (121.133.177.171) 2.04ms
2017-08-15 07:19:03,504 - tornado.access - web.py[line:1971] - WARNING - 405 GET /tree (121.133.177.171) 1.99ms
2017-08-15 07:47:49,032 - tornado.access - web.py[line:1971] - WARNING - 405 GET /terminals (121.133.177.171) 1.99ms
2017-08-15 08:25:12,580 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
