2017-08-09 22:12:23,865 - tornado.access - web.py[line:1971] - WARNING - 405 GET /login (27.102.102.19) 2.31ms
2017-08-10 09:20:02,999 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-10 10:01:05,617 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://clientapi.ipip.net/echo.php?info=1234567890 (139.162.81.62) 2.70ms
2017-08-10 18:54:14,389 - tornado.access - web.py[line:1971] - WARNING - 404 GET /robots.txt (127.0.0.1) 1.56ms
2017-08-10 19:21:48,747 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.201.45) 1.96ms
2017-08-10 20:10:34,180 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://www.server110.com/ (122.228.208.106) 1.94ms
2017-08-10 20:10:34,354 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.linode.com:443 (122.228.208.106) 1.08ms
2017-08-10 20:10:36,847 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.linode.com:443 (122.228.208.106) 1.08ms
2017-08-10 20:15:42,326 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.201.45) 1.96ms
